SSEG SEGMENT 'STACK'
      DW 32H DUP(0)
SSEG ENDS

DSEG SEGMENT 'DATA'
      PARALIST LABEL BYTE
      MAXLEN DB 100
      ACTLEN DB ?
      KBDATA DB 20 DUP(0)
DSEG ENDS

CSEG SEGMENT 'CODE'
ASSUME CS:CSEG,DS:DSEG,SS:SSEG
MAIN PROC NEAR
      MOV AX,DSEG
      MOV DS,AX
      MOV AH,0AH
      MOV DX,OFFSET PARALIST
      INT 21H
      LEA DI,KBDATA
AGAIN:CMP BYTE PTR[DI],'a'
      JB NEXT
      CMP BYTE PTR[DI],'z'
      JA NEXT
      SUB BYTE PTR[DI],20H
NEXT: INC DI
      DEC ACTLEN
      JNZ AGAIN
      MOV BYTE PTR[DI],'$'    
      MOV AH,9
      MOV DX,OFFSET KBDATA
      INT 21H
      MOV AX,4C00H
      INT 21H
MAIN ENDP
CSEG ENDS
END MAIN